### ISSUE TITLE
List of unhandles commands

### ISSUE THREAD

**Issue by tumidi** [innodoc/innoconv#20]
## tub_mathe

- [x] `Could not handle command -` *fixed in content*
- [x] `Could not handle command :` *fixed in content*
- [ ] tabular  
      (there are tabular without surrounding table env. maybe just wrap them with a table and run parse_fragment on them?)
- [x] noindent 914fe74dae708ad32939cb9b35f7c6f5b4a893e6
- [x] MSubsubsectionx 35c81578d7c589b97570bb9a46fe859921e1e170
- [x] tikzpicture (without `\MTikzAuto`??) *fixed in content*
- [x] mequationitem 7049cd8626546d7ea1dd32d84b2213e6b70da70a
- [x] html 0dcd93786d09bd07e35639be6f9acd0028ffefde
- [x] MDFPeriod outside math *fixed in content*
- [x] MTest 304c38e1af180d09b77af44c81bfb3ad028f2adb
- [x] MXInfo 90c0edeed457992027d2d2ea4a52deab9f9f8af3
- [x] highlight c233d000f68dc37c8f0ed152a68e9bc4a7be66a7
- [x] modsemph c233d000f68dc37c8f0ed152a68e9bc4a7be66a7
- [x] modstextbf c233d000f68dc37c8f0ed152a68e9bc4a7be66a7
- [x] clearpage 69f0a23b437f0d4ac8825ae7d19b06a80de95ec5
- [x] medskip ebec67795fb953136936caa1f5b52a9a2486c86d
- [x] newline a6234362d525d3c0bad6ef5e95fc8968a22d5086
- [x] MVideo 362f7801f0710a8ad2d1b8e3d7ef2e3c86abe95a
- [x] MContent 4207fdd0bf456b6f92a39453d2fc7460055f0a4e
- [x] hspace and hspace* e145810d1c2961eaa1204979023f138d70c27806
- [x] MZahl (not in Math) 79f8d6ffe7445057267a12efc020da25499a3020
- [x] MSubsubsection 533641b6f7d63584416275faa0ad40c763559a87
- [x] MSubsubsubsectionx 09909b443824b8c77a3fe90aaddfe0f30cd32954
- [x] ~~itemize~~
- [x] MContentTable 3c4fd9e87805703af7c95965f97282ee058c45f7
- [x] MGlobalStart 3c4fd9e87805703af7c95965f97282ee058c45f7
- [x] MPullSite 3c4fd9e87805703af7c95965f97282ee058c45f7
- [x] MWatermarkSettings 3c4fd9e87805703af7c95965f97282ee058c45f7
- [x] MGlobal*Tag 3c4fd9e87805703af7c95965f97282ee058c45f7
- [x] `\-` (used for word splitting - https://de.wikibooks.org/wiki/LaTeX-W%C3%B6rterbuch:_Silbentrennung)

### Template Commands
These load content from other files and/or occur more often during the course
- [ ] MCopyrightCollection (a dynamically generated list of copyrighted course content, see https://guest6.mulf.tu-berlin.de/math/html/3.1.1/xcontent3.html, what do we do with it?
- [x] jhtmlhinweiseingabefunktionenexp (calls `\iFunctionInputHint` which is defined in `de.tex`/`en.tex` and print some help for specific types of exercises
- [x] jhtmlhinweiseingabefunktionen (same as above)
- [x] mformelzoomhint (same as above)

### Exercise Commands / Environments
All commands related to exercises
- [x] MLParsedQuestion
- [x] MLSimplifyQuestion
- [x] MLFunctionQuestion
- [ ] MDirectRouletteExercises
- [ ] MSetPoints
- [x] MLCheckbox
- [x] MLIntervalQuestion
- [ ] MGroupButton (handle evaluation of exercise groups)
- [x] MLQuestion
- [ ] \begin{MExerciseCollection} (collection of exercises: mintmod.tex states something about database pulled exercises...)
- [ ] \begin{MQuestionGroup}

### Math

- [x] MCOSHZusatz 1dfc5747940be6e3887d2b56852da747cef5c692
- [x] MBinom 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] MDVec 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] MVec 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] MTextSF 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] MUnderset 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] MEmptyset 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] ML 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] MDwSp 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] MHDots 1bf6e778fb4f155f393e89bfb4183f3edb357109
- [x] MGrad 6258054c80b3c86d3b29eddbfc14108b08b67f97
- [x] MSep 6258054c80b3c86d3b29eddbfc14108b08b67f97
- [x] Mvarphi eeb2762e89e6d0e5ff82ba7a9dafe9b6cbf19928
- [x] function 421f6b71ceb2437f8561f4685b860dab50cb8e8d
- [x] `{R}` etc. eeb2762e89e6d0e5ff82ba7a9dafe9b6cbf19928
- [x] MRelates d1ba7edb1a1d28b05d709b98fa2126710f785499
- [x] Mmapsto d1ba7edb1a1d28b05d709b98fa2126710f785499
- [x] MD d1ba7edb1a1d28b05d709b98fa2126710f785499
- [x] Id d1ba7edb1a1d28b05d709b98fa2126710f785499
- [x] MGeoAbstand 6258054c80b3c86d3b29eddbfc14108b08b67f97
- [x] MGeoStrecke 6258054c80b3c86d3b29eddbfc14108b08b67f97
- [x] MGeoDreieck 6258054c80b3c86d3b29eddbfc14108b08b67f97
- [x] MGeoGerade 6258054c80b3c86d3b29eddbfc14108b08b67f97
- [x] null eeb2762e89e6d0e5ff82ba7a9dafe9b6cbf19928
- [x] lto eeb2762e89e6d0e5ff82ba7a9dafe9b6cbf19928
- [x] Mid 8ef40811c715076f15210e5dc5c25e3d3075725e
- [x] MTSP 8ef40811c715076f15210e5dc5c25e3d3075725e
- [x] Mmeasuredangle b658e3e09581905b98150cc320f0df7ff2a76cde
- [x] MOhm 710e024183e9a08223d117d91c125d9a26583943
- [x] Mvarepsilon e9c1114afc06c0a087d881ae035721de99c5f12c
- [x] ld 94b3633748430e0fc55cbca99059a150b1ec1473

*These are special, we need to parse arguments as they may contain commands!*

- [x] MPointTwo 48f721375c69e34f793cd40173532c12f66a5b4a
- [x] MPointTwoAS 48f721375c69e34f793cd40173532c12f66a5b4a
- [x] MPointThree 48f721375c69e34f793cd40173532c12f66a5b4a
- [x] MPointThreeAS 48f721375c69e34f793cd40173532c12f66a5b4a
- [x] MVector 48f721375c69e34f793cd40173532c12f66a5b4a
- [x] MCases d1ba7edb1a1d28b05d709b98fa2126710f785499
- [x] MEinheit 6c134143c0462933987f59c7103b33ced7155024, 540878fc8a937312ce176121d960fa34def0322f
- [x] `\begin{MCaseEnv}` 186b56a1bdf03abe0b2e7b65ac1a4807e7dd3f7c

**Comment by tumidi** [comment]
marked the checklist item **MVideo** as completed

**Comment by tumidi** [comment]
marked the checklist item **hspace and hspace* e145810d1c2961eaa1204979023f138d70c27806** as completed

**Comment by tumidi** [comment]
marked the checklist item **MDwSp** as completed

**Comment by tumidi** [comment]
marked the checklist item **MEmptyset** as completed

**Comment by tumidi** [comment]
marked the checklist item **ML** as completed

**Comment by tumidi** [comment]
marked the checklist item **MUnderset** as completed

**Comment by tumidi** [comment]
marked the checklist item **MCOSHZusatz** as completed

**Comment by tumidi** [comment]
marked the checklist item **MBinom** as completed

**Comment by tumidi** [comment]
marked the checklist item **MTextSF** as completed

**Comment by tumidi** [comment]
marked the checklist item **MVec** as completed

**Comment by tumidi** [comment]
marked the checklist item **MDVec** as completed

**Comment by tumidi** [comment]
marked the checklist item **MVector** as completed

**Comment by tumidi** [comment]
marked the checklist item **MPointTwo** as completed

**Comment by tumidi** [comment]
marked the checklist item **MPointTwo** as incomplete

**Comment by tumidi** [comment]
marked the checklist item **clearpage** as completed

**Comment by tumidi** [comment]
In GitLab by @ghost on Apr 11, 2018, 16:14

marked the task **MCases** as completed

 *By Niklas Plessing on 2018-04-11T14:14:16 (imported from GitLab)*

**Comment by tumidi** [comment]
marked the checklist item **MOhm** as completed

**Comment by tumidi** [comment]
In GitLab by @ghost on Apr 16, 2018, 08:41

marked the task **`\-` (used for word splitting - https://de.wikibooks.org/wiki/LaTeX-W%C3%B6rterbuch:_Silbentrennung)** as completed

 *By Niklas Plessing on 2018-04-16T06:41:46 (imported from GitLab)*

**Comment by tumidi** [comment]
marked the checklist item **`\begin{MCaseEnv}`** as completed

**Comment by tumidi** [comment]
marked the checklist item **html (to be converted to LaTeX / markdown)** as completed

**Comment by tumidi** [comment]
marked the checklist item **`Could not handle command -`** as completed

**Comment by tumidi** [comment]
marked the checklist item **MDFPeriod outside math** as completed

**Comment by tumidi** [comment]
marked the checklist item **tikzpicture (without `\MTikzAuto`??)** as completed

**Comment by tumidi** [comment]
In GitLab by @ghost on May 7, 2018, 16:58

marked the task **MLParsedQuestion** as completed

 *By Niklas Plessing on 2018-05-07T14:58:05 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 7, 2018, 16:58

marked the task **MLSimplifyQuestion** as completed

 *By Niklas Plessing on 2018-05-07T14:58:07 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 7, 2018, 16:58

marked the task **MLSimplifyQuestion** as incomplete

 *By Niklas Plessing on 2018-05-07T14:58:39 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 7, 2018, 16:58

marked the task **MLQuestion** as completed

 *By Niklas Plessing on 2018-05-07T14:58:48 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 16, 2018, 15:59

marked the task **MLFunctionQuestion** as completed

 *By Niklas Plessing on 2018-05-16T13:59:05 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 16, 2018, 15:59

marked the task **MLSimplifyQuestion** as completed

 *By Niklas Plessing on 2018-05-16T13:59:06 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 16, 2018, 15:59

marked the task **MLIntervalQuestion** as completed

 *By Niklas Plessing on 2018-05-16T13:59:06 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 16, 2018, 15:59

marked the task **MLCheckbox** as completed

 *By Niklas Plessing on 2018-05-16T13:59:24 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 16, 2018, 16:05

marked the task **mformelzoomhint (same as above)** as completed

 *By Niklas Plessing on 2018-05-16T14:05:19 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 16, 2018, 16:28

marked the task **jhtmlhinweiseingabefunktionenexp (calls `\iFunctionInputHint` which is defined in `de.tex`/`en.tex` and print some help for specific types of exercises** as completed

 *By Niklas Plessing on 2018-05-16T14:28:30 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on May 22, 2018, 12:11

marked the task **jhtmlhinweiseingabefunktionen (same as above)** as completed

 *By Niklas Plessing on 2018-05-22T10:11:11 (imported from GitLab)*

**Comment by tumidi** [comment]
moved to innoconv-mintmod#2
