### ISSUE TITLE
Ideas for other filters/post-processing

### ISSUE THREAD

**Issue by tumidi** [innodoc/innoconv#5]
Currently it looks like we need other post-processing in addition to `mintmod_filter`. This may be implemented in additional Pandoc filters or other means of post-processing the Pandoc output.

## Ideas for filters/post-processing

- [ ] Automatic numbering of sections, equations, and so forth…
- [x] Generate table of contents
- [x] Cut document into separate HTML pages according to header level (e.g. make all level 3 sections appear on a separate HTML page)
- [x] Create an index #14
- [x] `\ifttm \else \fi` conditionals #15
- [ ] Insert a dynamic media path for all images

*At some point we're going to open an issues for each point. Add issue numbers here then!*

### Fixing content structure

- [ ] Remove `P` inside `LI` tags
- [ ] Remove `DIV` inside `P`
- [ ] Join sequences of `Str` and `Space` into single `Str` (smaller file size/performance)

## Motivation

The reasons are manifold:

*Note: These problems have been solved by using panzer* #12.

- ~~For parsing unknown LaTeX environments panflute needs to call Pandoc in a subprocess.  
  This imposes problems: We cannot easily remember information and pass it to the subprocess where it might be needed.  
  *Example*: When encountering `MLabel` command, we would need to remember the last header element in order to insert the `id` attribute. Some section-like commands are implemented as environments. Within the spawned process that parses this environment we can't access the "outer" document data structure where the last header is "remembered".  
  *Possible solution*: Create a post-processing filter that runs after converting mintmod commands. It would "see" the document as a whole and would just do the job of inserting IDs into the header elements while discarding the corresponding labels.~~

- ~~Separation of concerns: Strive for cleaner code by separating functionality.~~
  - ~~Enable/disable filters one by one~~
  - ~~Modular approach in contrast to one monolithic filter~~

- ~~We don't have access to the `Doc` object in subprocesses.  
  E.g. `doc.format.beginswith('html5')` would not work.~~
~~

**Comment by tumidi** [comment]
In GitLab by @ghost on Mar 1, 2018, 15:25

marked the task **`\if \else \fi` conditionals** as completed

 *By Niklas Plessing on 2018-03-01T14:25:59 (imported from GitLab)*

**Comment by tumidi** [comment]
In GitLab by @ghost on Mar 1, 2018, 15:26

marked the task **Create an index page** as completed

 *By Niklas Plessing on 2018-03-01T14:26:04 (imported from GitLab)*

**Comment by tumidi** [comment]
marked the checklist item **Create an index page** as incomplete

**Comment by tumidi** [comment]
marked the checklist item **Create an index page** as completed

**Comment by tumidi** [comment]
marked the checklist item **Create an index page** as incomplete

**Comment by tumidi** [comment]
marked the checklist item **Generate table of contents** as completed

**Comment by tumidi** [comment]
marked the checklist item **Cut document into separate HTML pages according to header level (e.g. make all level 3 sections appear on a separate HTML page)** as completed

**Comment by tumidi** [comment]
marked the checklist item **Create an index #14** as completed

**Comment by tumidi** [comment]
moved to innoconv-mintmod#3
